export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    PostgrestVersion: '12';
    Tables: {
      projects: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          source_type: 'github_url' | 'zip_upload' | 'manual';
          source_url: string | null;
          source_metadata: Json | null;
          analysis_status: 'pending' | 'analyzing' | 'completed' | 'failed';
          analysis_summary: string | null;
          analysis_completed_at: string | null;
          patent_strength_score: number | null;
          patent_strength_rating: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          source_type: 'github_url' | 'zip_upload' | 'manual';
          source_url?: string | null;
          source_metadata?: Json | null;
          analysis_status?: string;
          analysis_summary?: string | null;
          analysis_completed_at?: string | null;
          patent_strength_score?: number | null;
          patent_strength_rating?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          source_type?: string;
          source_url?: string | null;
          source_metadata?: Json | null;
          analysis_status?: string;
          analysis_summary?: string | null;
          analysis_completed_at?: string | null;
          patent_strength_score?: number | null;
          patent_strength_rating?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_files: {
        Row: {
          id: string;
          project_id: string;
          file_path: string;
          language: string | null;
          line_count: number | null;
          content_hash: string | null;
          analysis_summary: string | null;
          extracted_features: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          file_path: string;
          language?: string | null;
          line_count?: number | null;
          content_hash?: string | null;
          analysis_summary?: string | null;
          extracted_features?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          file_path?: string;
          language?: string | null;
          line_count?: number | null;
          content_hash?: string | null;
          analysis_summary?: string | null;
          extracted_features?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      extracted_features: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          type: string;
          description: string;
          technical_details: string;
          source_files: string[] | null;
          code_snippets: Json | null;
          novelty_strength: string | null;
          is_core_innovation: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          type: string;
          description: string;
          technical_details: string;
          source_files?: string[] | null;
          code_snippets?: Json | null;
          novelty_strength?: string | null;
          is_core_innovation?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string;
          type?: string;
          description?: string;
          technical_details?: string;
          source_files?: string[] | null;
          code_snippets?: Json | null;
          novelty_strength?: string | null;
          is_core_innovation?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      patent_applications: {
        Row: {
          id: string;
          project_id: string;
          user_id: string;
          title: string | null;
          status: string;
          abstract: string | null;
          specification: string | null;
          field_of_invention: string | null;
          background_art: string | null;
          summary_invention: string | null;
          detailed_description: string | null;
          prior_art_search_status: string;
          prior_art_search_completed_at: string | null;
          novelty_score: number | null;
          novelty_analysis_id: string | null;
          differentiation_analysis: string | null;
          claims_generation_status: string;
          drawings_generation_status: string;
          specification_generation_status: string;
          full_application_status: string;
          metadata: Json | null;
          inventors: Json | null;
          entity_status: string | null;
          correspondence_address: Json | null;
          attorney_info: Json | null;
          cpc_classification: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          user_id: string;
          title?: string | null;
          status?: string;
          abstract?: string | null;
          specification?: string | null;
          field_of_invention?: string | null;
          background_art?: string | null;
          summary_invention?: string | null;
          detailed_description?: string | null;
          prior_art_search_status?: string;
          prior_art_search_completed_at?: string | null;
          novelty_score?: number | null;
          novelty_analysis_id?: string | null;
          differentiation_analysis?: string | null;
          claims_generation_status?: string;
          drawings_generation_status?: string;
          specification_generation_status?: string;
          full_application_status?: string;
          metadata?: Json | null;
          inventors?: Json | null;
          entity_status?: string | null;
          correspondence_address?: Json | null;
          attorney_info?: Json | null;
          cpc_classification?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          user_id?: string;
          title?: string | null;
          status?: string;
          abstract?: string | null;
          specification?: string | null;
          field_of_invention?: string | null;
          background_art?: string | null;
          summary_invention?: string | null;
          detailed_description?: string | null;
          prior_art_search_status?: string;
          prior_art_search_completed_at?: string | null;
          novelty_score?: number | null;
          novelty_analysis_id?: string | null;
          differentiation_analysis?: string | null;
          claims_generation_status?: string;
          drawings_generation_status?: string;
          specification_generation_status?: string;
          full_application_status?: string;
          metadata?: Json | null;
          inventors?: Json | null;
          entity_status?: string | null;
          correspondence_address?: Json | null;
          attorney_info?: Json | null;
          cpc_classification?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      patent_claims: {
        Row: {
          id: string;
          application_id: string;
          claim_number: number;
          claim_type: string;
          claim_text: string;
          parent_claim_id: string | null;
          status: string;
          category: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          application_id: string;
          claim_number: number;
          claim_type?: string;
          claim_text: string;
          parent_claim_id?: string | null;
          status?: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          application_id?: string;
          claim_number?: number;
          claim_type?: string;
          claim_text?: string;
          parent_claim_id?: string | null;
          status?: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      patent_drawings: {
        Row: {
          id: string;
          application_id: string;
          figure_number: number;
          title: string;
          description: string | null;
          svg_content: string | null;
          image_url: string | null;
          drawing_type: string;
          callouts: Json;
          blocks: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          application_id: string;
          figure_number: number;
          title: string;
          description?: string | null;
          svg_content?: string | null;
          image_url?: string | null;
          drawing_type?: string;
          callouts?: Json;
          blocks?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          application_id?: string;
          figure_number?: number;
          title?: string;
          description?: string | null;
          svg_content?: string | null;
          image_url?: string | null;
          drawing_type?: string;
          callouts?: Json;
          blocks?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      patent_prior_art_results: {
        Row: {
          id: string;
          application_id: string;
          patent_number: string | null;
          title: string | null;
          abstract: string | null;
          relevance_score: number | null;
          similarity_score: number | null;
          source: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          application_id: string;
          patent_number?: string | null;
          title?: string | null;
          abstract?: string | null;
          relevance_score?: number | null;
          similarity_score?: number | null;
          source?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          application_id?: string;
          patent_number?: string | null;
          title?: string | null;
          abstract?: string | null;
          relevance_score?: number | null;
          similarity_score?: number | null;
          source?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      patent_novelty_analyses: {
        Row: {
          id: string;
          application_id: string;
          overall_score: number | null;
          approval_probability: number | null;
          strength_rating: string | null;
          analysis_data: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          application_id: string;
          overall_score?: number | null;
          approval_probability?: number | null;
          strength_rating?: string | null;
          analysis_data?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          application_id?: string;
          overall_score?: number | null;
          approval_probability?: number | null;
          strength_rating?: string | null;
          analysis_data?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      copyright_registrations: {
        Row: {
          id: string;
          project_id: string;
          user_id: string;
          title: string;
          registration_type: string;
          work_type: string;
          status: string;
          description: string | null;
          author_name: string | null;
          author_type: string;
          contains_ai_generated_content: boolean;
          ai_contribution_percentage: number;
          ai_tools_used: string[] | null;
          human_authorship_statement: string | null;
          application_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          user_id: string;
          title: string;
          registration_type: string;
          work_type: string;
          status?: string;
          description?: string | null;
          author_name?: string | null;
          author_type?: string;
          contains_ai_generated_content?: boolean;
          ai_contribution_percentage?: number;
          ai_tools_used?: string[] | null;
          human_authorship_statement?: string | null;
          application_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          user_id?: string;
          title?: string;
          registration_type?: string;
          work_type?: string;
          status?: string;
          description?: string | null;
          author_name?: string | null;
          author_type?: string;
          contains_ai_generated_content?: boolean;
          ai_contribution_percentage?: number;
          ai_tools_used?: string[] | null;
          human_authorship_statement?: string | null;
          application_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      trademark_applications: {
        Row: {
          id: string;
          project_id: string;
          user_id: string;
          mark_type: string;
          mark_text: string | null;
          mark_description: string | null;
          international_class: number | null;
          goods_services_description: string | null;
          filing_basis: string;
          owner_name: string | null;
          owner_type: string;
          status: string;
          application_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          user_id: string;
          mark_type?: string;
          mark_text?: string | null;
          mark_description?: string | null;
          international_class?: number | null;
          goods_services_description?: string | null;
          filing_basis?: string;
          owner_name?: string | null;
          owner_type?: string;
          status?: string;
          application_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          user_id?: string;
          mark_type?: string;
          mark_text?: string | null;
          mark_description?: string | null;
          international_class?: number | null;
          goods_services_description?: string | null;
          filing_basis?: string;
          owner_name?: string | null;
          owner_type?: string;
          status?: string;
          application_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
