import type { Context } from "@netlify/functions";

const CLAUDE_MODEL = "claude-sonnet-4-20250514";
const ANTHROPIC_API = "https://api.anthropic.com/v1/messages";

const FEATURE_TOKEN_LIMITS: Record<string, number> = {
  patent_specification: 4096,
  patent_claims: 8192,
  patent_prior_art_search: 4096,
  patent_prior_art_comparison: 4096,
  patent_novelty_analysis: 4096,
  patent_drawings: 4096,
  patent_drawing_generation: 16384,
  patent_callout_enhancement: 2048,
  cpc_classification: 2048,
  codebase_analysis: 4096,
  feature_synthesis: 4096,
  copyright_analysis: 2048,
  trademark_analysis: 2048,
  default: 2048,
};

interface GenerateRequest {
  prompt: string;
  featureArea?: string;
  maxTokens?: number;
  temperature?: number;
}

export default async function handler(req: Request, _context: Context) {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { "Content-Type": "application/json" },
    });
  }

  const apiKey = Netlify.env.get("ANTHROPIC_API_KEY");
  if (!apiKey) {
    return new Response(
      JSON.stringify({ error: "ANTHROPIC_API_KEY not configured" }),
      { status: 503, headers: { "Content-Type": "application/json" } }
    );
  }

  let body: GenerateRequest;
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid JSON body" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (!body.prompt) {
    return new Response(JSON.stringify({ error: "prompt is required" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const featureArea = body.featureArea || "default";
  const maxTokens =
    body.maxTokens || FEATURE_TOKEN_LIMITS[featureArea] || 2048;
  const temperature = body.temperature ?? 0.3;

  try {
    const response = await fetch(ANTHROPIC_API, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: CLAUDE_MODEL,
        max_tokens: maxTokens,
        temperature,
        messages: [{ role: "user", content: body.prompt }],
      }),
      signal: AbortSignal.timeout(90000),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      const status =
        response.status === 429
          ? 429
          : response.status === 401
            ? 401
            : 502;
      return new Response(
        JSON.stringify({
          error:
            status === 429
              ? "Rate limit exceeded"
              : status === 401
                ? "Invalid API key"
                : `Claude API error (${response.status})`,
          detail: errorBody.substring(0, 500),
        }),
        { status, headers: { "Content-Type": "application/json" } }
      );
    }

    const data = await response.json();
    const text = data?.content?.[0]?.text;
    if (!text) {
      return new Response(
        JSON.stringify({ error: "No text generated by Claude" }),
        { status: 502, headers: { "Content-Type": "application/json" } }
      );
    }

    return new Response(
      JSON.stringify({
        text,
        stopReason: data.stop_reason,
        usage: data.usage,
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  } catch (err: any) {
    return new Response(
      JSON.stringify({
        error:
          err.name === "TimeoutError"
            ? "Request timed out"
            : "AI generation failed",
        detail: err.message,
      }),
      { status: 502, headers: { "Content-Type": "application/json" } }
    );
  }
}
