import { Shield, ArrowLeft } from 'lucide-react';

interface TermsOfServiceProps {
  onBack: () => void;
}

export function TermsOfService({ onBack }: TermsOfServiceProps) {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white sticky top-0 z-50 shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center gap-4">
          <button
            onClick={onBack}
            className="p-2 text-gray-400 hover:text-gray-700 rounded-xl hover:bg-gray-100 transition-all"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 bg-gradient-to-br from-indigo-600 to-violet-600 rounded-xl flex items-center justify-center shadow-sm">
              <Shield className="w-4.5 h-4.5 text-white" />
            </div>
            <span className="text-lg font-bold bg-gradient-to-r from-indigo-700 to-violet-600 bg-clip-text text-transparent">
              Git-Patent
            </span>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: April 8, 2026</p>

        <div className="prose prose-gray max-w-none space-y-8 text-sm leading-relaxed text-gray-700">
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Git-Patent ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the Service. The Service is provided by the operator of Git-Patent ("the Company," "we," "us," or "our").
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">2. Description of Service</h2>
            <p>
              Git-Patent is an AI-powered tool that analyzes source code repositories and generates draft patent application materials, including but not limited to specifications, claims, abstracts, drawings, and prior art search results. The Service is provided on an "as-is" and "as-available" basis.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">3. AI-Generated Content Disclaimer</h2>
            <p>
              <strong>All output produced by the Service is generated by artificial intelligence and is provided on a best-effort basis only.</strong> AI-generated content may contain errors, omissions, inaccuracies, or hallucinations. The Service does not guarantee the accuracy, completeness, legal sufficiency, or fitness for any particular purpose of any generated materials.
            </p>
            <p className="mt-3">
              Generated patent application materials are <strong>preliminary drafts only</strong> and do not constitute filed patent applications, legal opinions, or legal advice of any kind. The Company makes no representation that any output will meet the requirements of the United States Patent and Trademark Office (USPTO) or any other patent authority.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">4. No Legal Advice; Consult an Attorney</h2>
            <p>
              <strong>The Service does not provide legal advice.</strong> Nothing produced by the Service should be construed as legal counsel or a substitute for the advice of a qualified, licensed patent attorney or patent agent. You are solely responsible for reviewing, verifying, and validating all output before relying on it or submitting it to any government agency or third party.
            </p>
            <p className="mt-3">
              <strong>You should consult a licensed patent attorney or patent agent</strong> before filing any patent application, making any intellectual property decisions, or relying on any materials generated by the Service. The Company strongly recommends independent legal review of all generated content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">5. No Obligation or Guarantee</h2>
            <p>
              The Company assumes no obligation to you or any third party regarding the Service or its output. Without limiting the foregoing, the Company does not guarantee that:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1.5">
              <li>Generated materials will be patentable, novel, non-obvious, or meet any statutory requirements</li>
              <li>Prior art searches will be complete or identify all relevant prior art</li>
              <li>Novelty scores, patentability assessments, or any other analyses will be accurate</li>
              <li>The Service will be available, uninterrupted, error-free, or secure</li>
              <li>Any particular result or outcome will be achieved through use of the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">6. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, SUCCESSORS, OR ASSIGNS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, DATA, BUSINESS OPPORTUNITIES, PATENT RIGHTS, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE), EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p className="mt-3">
              THE COMPANY'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU HAVE PAID TO THE COMPANY IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">7. Hold Harmless and Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless the Company, its officers, directors, employees, agents, affiliates, successors, and assigns from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising out of or related to:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1.5">
              <li>Your use of the Service or any output generated by the Service</li>
              <li>Your reliance on AI-generated content without independent legal review</li>
              <li>Any patent application you file or cause to be filed based in whole or in part on materials generated by the Service</li>
              <li>Any intellectual property dispute, claim, or proceeding arising from your use of the Service</li>
              <li>Your violation of these Terms or any applicable law or regulation</li>
              <li>Any third-party claim related to your use of the Service or its output</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">8. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">9. User Responsibilities</h2>
            <p>You acknowledge and agree that:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1.5">
              <li>You are solely responsible for determining the suitability and accuracy of any output for your purposes</li>
              <li>You will not submit any AI-generated materials to the USPTO or any other authority without thorough review by a qualified professional</li>
              <li>You bear all risk associated with your use of the Service and its output</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials</li>
              <li>You will comply with all applicable laws and regulations in your use of the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">10. Intellectual Property</h2>
            <p>
              You retain ownership of any source code or materials you upload to the Service. The Company claims no ownership rights over your input materials or the output generated from them. However, the Company retains all rights in the Service itself, including its algorithms, models, prompts, and software.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">11. Payment and Refund Policy</h2>
            <p>
              Fees for the Service are charged on a per-project basis as displayed at the time of purchase. All payments are processed through Stripe. Fees are non-refundable except as required by applicable law. The Company reserves the right to modify pricing at any time.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">12. Modification of Terms</h2>
            <p>
              The Company reserves the right to modify these Terms at any time. Continued use of the Service after any such modifications constitutes your acceptance of the revised Terms. It is your responsibility to review these Terms periodically for changes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">13. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Ohio, without regard to its conflict of law provisions. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in Hamilton County, Ohio.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">14. Severability</h2>
            <p>
              If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect. The invalid or unenforceable provision shall be modified to the minimum extent necessary to make it valid and enforceable.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">15. Entire Agreement</h2>
            <p>
              These Terms constitute the entire agreement between you and the Company regarding the Service and supersede all prior agreements, understandings, and communications, whether written or oral, relating to the subject matter hereof.
            </p>
          </section>

          <section className="border-t border-gray-200 pt-8 mt-10">
            <p className="text-xs text-gray-400">
              If you have questions about these Terms, please contact us through the channels provided on the Service.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
