const GEMINI_MODEL = 'gemini-2.5-flash';
const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta/models';

export interface GenerateTextOptions {
  maxTokens?: number;
  temperature?: number;
  topP?: number;
}

const FEATURE_TOKEN_LIMITS: Record<string, number> = {
  patent_specification: 3000,
  patent_claims: 2000,
  patent_prior_art_search: 2000,
  patent_drawings: 1500,
  cpc_classification: 2000,
  codebase_analysis: 3000,
  feature_synthesis: 2000,
  copyright_analysis: 1500,
  trademark_analysis: 1500,
  default: 1500,
};

function getGeminiApiKey(): string {
  const key = import.meta.env.VITE_GEMINI_API_KEY;
  if (!key) throw new Error('VITE_GEMINI_API_KEY not configured');
  return key;
}

export function checkGeminiConfiguration(): { configured: boolean; error?: string } {
  try {
    getGeminiApiKey();
    return { configured: true };
  } catch {
    return { configured: false, error: 'Gemini API key not set' };
  }
}

export async function generateText(
  prompt: string,
  featureArea?: string,
  options?: GenerateTextOptions
): Promise<string> {
  const apiKey = getGeminiApiKey();
  const maxTokens = options?.maxTokens || FEATURE_TOKEN_LIMITS[featureArea || 'default'] || 1500;
  const temperature = options?.temperature ?? 0.3;

  const url = `${GEMINI_API_BASE}/${GEMINI_MODEL}:generateContent?key=${apiKey}`;

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        maxOutputTokens: maxTokens,
        temperature,
        topP: options?.topP ?? 0.95,
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    if (response.status === 429) {
      throw new Error('Rate limit exceeded. Please wait a moment and try again.');
    }
    throw new Error(`Gemini API error (${response.status}): ${errorText}`);
  }

  const data = await response.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('No text generated by Gemini');
  return text;
}
