/**
 * AI Service — Anthropic Claude (via server-side proxy)
 *
 * Small / fast calls go through the synchronous /.netlify/functions/ai-generate
 * proxy. Heavy calls (claims, novelty, prior-art, drawings, differentiation, …)
 * generate thousands of tokens on Opus/Sonnet and cannot finish within Netlify's
 * ~26s synchronous cap, so they route through a background function + polling,
 * which preserves full Opus/Sonnet quality. The API key never reaches the browser
 * in either path.
 */

export interface GenerateTextOptions {
  maxTokens?: number;
  temperature?: number;
  topP?: number;
}

/** Kept for backward compat — all services call this to check readiness */
export function checkGeminiConfiguration(): { configured: boolean; error?: string } {
  // The API key lives server-side now; we assume it's configured.
  // A missing key will surface as a 503 from the serverless function.
  return { configured: true };
}

// Features safe to run synchronously = SMALL, bounded output that always
// finishes within Netlify's ~26s cap: the per-section spec calls, the abstract,
// and the tiny feature-synthesis call. Everything else — including
// codebase_analysis / patent_feature_extraction, which can emit large outputs
// (measured: Haiku hits ~36s at 4096 tokens, past the sync cap) — routes through
// the background function (Haiku speed + 15-min budget, no timeout).
const SYNC_FEATURES = new Set<string>([
  'patent_specification_field',
  'patent_specification_background',
  'patent_specification_summary',
  'patent_specification_detailed',
  'patent_abstract_generation',
  'feature_synthesis',
]);

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function generateTextSync(
  prompt: string,
  featureArea: string,
  options?: GenerateTextOptions
): Promise<string> {
  console.log(`[AI] Calling Claude via proxy (${featureArea}) promptLen=${prompt.length}`);

  const controller = new AbortController();
  const timeout = setTimeout(() => {
    console.error(`[AI] Request timed out after 28s (${featureArea})`);
    controller.abort();
  }, 28000);

  try {
    const response = await fetch('/.netlify/functions/ai-generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt,
        featureArea,
        maxTokens: options?.maxTokens,
        temperature: options?.temperature,
      }),
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ error: `HTTP ${response.status}` }));
      console.error(`[AI] Proxy error ${response.status}:`, errorData);
      if (response.status === 429) {
        throw new Error('Rate limit exceeded. Please wait a moment and try again.');
      }
      if (response.status === 401) {
        throw new Error('Invalid Anthropic API key configured on server.');
      }
      throw new Error(errorData.error || `Claude API error (${response.status})`);
    }

    const data = await response.json();
    if (!data.text) throw new Error('No text generated by Claude');

    if (data.stopReason === 'max_tokens') {
      console.warn(`[AI] Response TRUNCATED (${featureArea}) — hit token limit. responseLen=${data.text.length}`);
    }
    console.log(`[AI] Success (${featureArea}) responseLen=${data.text.length} stop=${data.stopReason}`);
    return data.text;
  } catch (err: any) {
    clearTimeout(timeout);
    if (err.name === 'AbortError') {
      throw new Error(`Claude API timed out after 28s (${featureArea})`);
    }
    console.error(`[AI] Fetch failed (${featureArea}):`, err.message || err);
    throw err;
  }
}

async function generateTextBackground(
  prompt: string,
  featureArea: string,
  options?: GenerateTextOptions
): Promise<string> {
  const jobId = crypto.randomUUID();
  console.log(`[AI] Background job ${jobId} (${featureArea}) promptLen=${prompt.length}`);

  const startResp = await fetch('/.netlify/functions/ai-generate-background', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      jobId,
      prompt,
      featureArea,
      maxTokens: options?.maxTokens,
      temperature: options?.temperature,
    }),
  });

  // Background functions return 202 (accepted). Anything else means it never started.
  if (!startResp.ok) {
    const detail = await startResp.text().catch(() => '');
    console.error(`[AI] Background start failed ${startResp.status} (${featureArea}):`, detail);
    throw new Error(`Failed to start AI job (${startResp.status})`);
  }

  const deadline = Date.now() + 300000; // poll up to 5 minutes
  let lastStatus = 'pending';
  while (Date.now() < deadline) {
    await sleep(2500);
    let job: any;
    try {
      const statusResp = await fetch(`/.netlify/functions/ai-job-status?jobId=${encodeURIComponent(jobId)}`);
      if (!statusResp.ok) continue;
      job = await statusResp.json();
    } catch {
      continue; // transient poll failure — keep trying
    }
    lastStatus = job?.status ?? lastStatus;
    if (job?.status === 'done') {
      if (!job.text) throw new Error('No text generated by Claude');
      if (job.stopReason === 'max_tokens') {
        console.warn(`[AI] Background response TRUNCATED (${featureArea}) responseLen=${job.text.length}`);
      }
      console.log(`[AI] Background success (${featureArea}) responseLen=${job.text.length} stop=${job.stopReason}`);
      return job.text;
    }
    if (job?.status === 'error') {
      console.error(`[AI] Background job error (${featureArea}):`, job.error);
      throw new Error(job.error || 'AI generation failed');
    }
    // pending — continue polling
  }

  throw new Error(`AI generation timed out after 5min (${featureArea}, last=${lastStatus})`);
}

export async function generateText(
  prompt: string,
  featureArea?: string,
  options?: GenerateTextOptions
): Promise<string> {
  const fa = featureArea || 'default';
  return SYNC_FEATURES.has(fa)
    ? generateTextSync(prompt, fa, options)
    : generateTextBackground(prompt, fa, options);
}
