/**
 * AI Service — Anthropic Claude (via server-side proxy)
 *
 * All API calls route through the Netlify serverless function
 * at /.netlify/functions/ai-generate so the API key never
 * reaches the browser.
 */

export interface GenerateTextOptions {
  maxTokens?: number;
  temperature?: number;
  topP?: number;
}

/** Kept for backward compat — all services call this to check readiness */
export function checkGeminiConfiguration(): { configured: boolean; error?: string } {
  // The API key lives server-side now; we assume it's configured.
  // A missing key will surface as a 503 from the serverless function.
  return { configured: true };
}

export async function generateText(
  prompt: string,
  featureArea?: string,
  options?: GenerateTextOptions
): Promise<string> {
  console.log(`[AI] Calling Claude via proxy (${featureArea || 'default'}) promptLen=${prompt.length}`);

  const controller = new AbortController();
  const timeout = setTimeout(() => {
    console.error(`[AI] Request timed out after 90s (${featureArea})`);
    controller.abort();
  }, 90000);

  try {
    const response = await fetch('/.netlify/functions/ai-generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt,
        featureArea: featureArea || 'default',
        maxTokens: options?.maxTokens,
        temperature: options?.temperature,
      }),
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ error: `HTTP ${response.status}` }));
      console.error(`[AI] Proxy error ${response.status}:`, errorData);
      if (response.status === 429) {
        throw new Error('Rate limit exceeded. Please wait a moment and try again.');
      }
      if (response.status === 401) {
        throw new Error('Invalid Anthropic API key configured on server.');
      }
      throw new Error(errorData.error || `Claude API error (${response.status})`);
    }

    const data = await response.json();
    if (!data.text) throw new Error('No text generated by Claude');

    if (data.stopReason === 'max_tokens') {
      console.warn(`[AI] Response TRUNCATED (${featureArea}) — hit token limit. responseLen=${data.text.length}`);
    }
    console.log(`[AI] Success (${featureArea}) responseLen=${data.text.length} stop=${data.stopReason}`);
    return data.text;
  } catch (err: any) {
    clearTimeout(timeout);
    if (err.name === 'AbortError') {
      throw new Error(`Claude API timed out after 90s (${featureArea})`);
    }
    console.error(`[AI] Fetch failed (${featureArea}):`, err.message || err);
    throw err;
  }
}
